apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversao
spec:
  replicas: 2
  selector:
    matchLabels:
      app: conversao
  template:
    metadata:
      labels:
        app: conversao
    spec:
      containers:
        - name: web
          image: fabricioveronez/conversao-distancia:v1
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: conversao
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
  selector:
    app: conversao