name: CI-CD

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
    CI:
        runs-on: ubuntu-latest
        steps:
            - name: Obetendo o código do projeto
              uses: actions/checkout@v5

            - name: Setup do Python
              uses: actions/setup-python@v6
              with:
                python-version: '3.13'
                
            - name: Instalação das dependências
              working-directory: ./src
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
            
            - name: Execução dos testes
              working-directory: ./src
              run: |
                python -m pytest tests/ -v
                

            - run: echo "Executar o Docker Build"
            - run: echo "Enviar a Imagem Docker para o Docker Hub"

    CD:
        runs-on: ubuntu-latest
        needs: [ CI ]
        steps:
            - run: echo "Obter o código"
            - run: echo "Configurar o Kubeconfig"
            - run: echo "Executar o apply"
